% Auto-generated by stereoCalibrator app on 08-Feb-2021
%-------------------------------------------------------


% Define images to process
imageFileNames1 = {'\\icnas3.cc.ic.ac.uk\eds17\Desktop\cvpr\Matlab\StereoImages\left\l1.jpg',...
    '\\icnas3.cc.ic.ac.uk\eds17\Desktop\cvpr\Matlab\StereoImages\left\l2.jpg',...
    '\\icnas3.cc.ic.ac.uk\eds17\Desktop\cvpr\Matlab\StereoImages\left\l3.jpg',...
    '\\icnas3.cc.ic.ac.uk\eds17\Desktop\cvpr\Matlab\StereoImages\left\l4.jpg',...
    '\\icnas3.cc.ic.ac.uk\eds17\Desktop\cvpr\Matlab\StereoImages\left\l5.jpg',...
    };
imageFileNames2 = {'\\icnas3.cc.ic.ac.uk\eds17\Desktop\cvpr\Matlab\StereoImages\right\r1.jpg',...
    '\\icnas3.cc.ic.ac.uk\eds17\Desktop\cvpr\Matlab\StereoImages\right\r2.jpg',...
    '\\icnas3.cc.ic.ac.uk\eds17\Desktop\cvpr\Matlab\StereoImages\right\r3.jpg',...
    '\\icnas3.cc.ic.ac.uk\eds17\Desktop\cvpr\Matlab\StereoImages\right\r4.jpg',...
    '\\icnas3.cc.ic.ac.uk\eds17\Desktop\cvpr\Matlab\StereoImages\right\r5.jpg',...
    };

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames1, imageFileNames2);

% Generate world coordinates of the checkerboard keypoints
squareSize = 25;  % in units of 'millimeters'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Read one of the images from the first stereo pair
I1 = imread(imageFileNames1{1});
[mrows, ncols, ~] = size(I1);

% Calibrate the camera
[stereoParams, pairsUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure; showReprojectionErrors(stereoParams);

% Visualize pattern locations
h2=figure; showExtrinsics(stereoParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, stereoParams);

% You can use the calibration data to rectify stereo images.
I2 = imread(imageFileNames2{1});
[J1, J2] = rectifyStereoImages(I1, I2, stereoParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('StereoCalibrationAndSceneReconstructionExample')
% showdemo('DepthEstimationFromStereoVideoExample')
