% Auto-generated by cameraCalibrator app on 04-Feb-2021
%-------------------------------------------------------


% Define images to process
imageDir = fullfile("fisheye");
imds = imageDatastore(imageDir);

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imds.Files);
imageFileNames = imds.Files(imagesUsed);

% Read the first image to obtain image size
originalImage = imread('fisheye/20210215_195158.jpg');
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates of the corners of the squares
squareSize = 25;  % in units of 'millimeters'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

[cameraParams2, imagesUsed2, estimationErrors2] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 3, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(originalImage, cameraParams);
undistortedImage2 = undistortImage(originalImage, cameraParams2);

img = cat(4,originalImage, undistortedImage, undistortedImage2);
figure;
montage(img,'Size',[1 3]);

%save("cameraParams.mat", "cameraParams");

% See additional examples of how to use the calibration data.  At the prompt type:
%showdemo('MeasuringPlanarObjectsExample')
%showdemo('StructureFromMotionExample')
